#ifndef ONSEM_SEMANTICTOTEXT_ENUM_SEMANTICTYPEOFFEEDBACK_HPP
#define ONSEM_SEMANTICTOTEXT_ENUM_SEMANTICTYPEOFFEEDBACK_HPP

namespace onsem {

enum class SemanticTypeOfFeedback { ASK_FOR_ADDITIONAL_INFORMATION, REACT_ON_SIMILARITIES, SENTIMENT };

}    // End of namespace onsem

#endif    // ONSEM_SEMANTICTOTEXT_ENUM_SEMANTICTYPEOFFEEDBACK_HPP
