#ifndef ONSEMSTREADATABASEGENERATOR_DATABASEPROVIDER_API_HPP
#define ONSEMSTREADATABASEGENERATOR_DATABASEPROVIDER_API_HPP

#include <onsem/common/exportsymbols/macro.hpp>

#if !defined(SWIG) && defined(onsemstreamdatabaseaccessor_EXPORTS)
    #define ONSEMSTREADATABASEGENERATOR_DATABASEPROVIDER_API SEMANTIC_LIB_API_EXPORTS(onsemstreamdatabaseaccessor)
#elif !defined(SWIG)
    #define ONSEMSTREADATABASEGENERATOR_DATABASEPROVIDER_API SEMANTIC_LIB_API(onsemstreamdatabaseaccessor)
#else
    #define ONSEMSTREADATABASEGENERATOR_DATABASEPROVIDER_API
#endif

#endif    // ONSEMSTREADATABASEGENERATOR_DATABASEPROVIDER_API_HPP
